services:
  - type: web
    name: hani-md
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm rebuild sharp
    startCommand: node start.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: PREFIXE
        value: "."
      - key: NOM_OWNER
        value: "H2025"
      - key: NUMERO_OWNER
        value: "225150252467"
      - key: MODE
        value: "public"
      - key: STICKER_PACK_NAME
        value: "HANI-MD"
      - key: STICKER_AUTHOR_NAME
        value: "H2025"
      - key: WAVE_NUMBER
        value: "225150252467"
      - key: MYSQL_HOST
        value: "mainline.proxy.rlwy.net"
      - key: MYSQL_PORT
        value: "14579"
      - key: MYSQL_USER
        value: "root"
      - key: MYSQL_PASSWORD
        value: "HjaFazWgJyqNlLQyWaAsazQpMnjdEdga"
      - key: MYSQL_DATABASE
        value: "railway"
      - key: MYSQL_URL
        value: "mysql://root:HjaFazWgJyqNlLQyWaAsazQpMnjdEdga@mainline.proxy.rlwy.net:14579/railway"
